- menu_name: "Quick Navigation"

- name: "About Us"
  url: "/about-us"
  title: "About Us"

- name: "Products"
  url: "/products"
  title: "Products"

- name: "OEM Service"
  url: "/oem-service"
  title: "OEM Service"
#
#- name: "News"
#  url: "/news"
#  title: "News"

- name: "Contact Us"
  url: "/contact"
  title: "Contact Us"
